proxy:
  useProxy: false
  proxy: "http://localhost:7890"
api:
api:
  binanceApiKey: "MqOFL1ygwXYF5DKgVKjis15rIpUMX39m5tUJwsde9L9UqYn3NJwvXgbFRPjnWw4d"
  binanceSecretKey: "UPf92SRhjzpWwJV9zjOPDGfR6Jd6C8CpQlfT7j73r6wXcMkNK2a2qdMVof49iLyF"
  mexcApiKey: "mx0vgleRm46vYrBG0j"
  mexcSecretKey: "fe57c67039be4032af80e8e5d3bd5218"
  mexcCookie: '_ga=GA1.1.1528609679.1685777703; _rdt_uuid=1685777702766.15c8f5e8-4930-4d23-b01b-4cd2b3d4e270; _fbp=fb.1.1685777703029.1652845116; x-mxc-fingerprint=g7rgl3TMTtUYYhH2GJtg; mxc_exchange_order_confirmation=[100]; mexc_fingerprint_visitorId=g7rgl3TMTtUYYhH2GJtg; _vid_t=FlWPF7bqi1Ug7CSDBd4tK8l2job4UByqDnXWn98cZVhq+eyXNahFEl1tVbsq5/Wg3MmxnRGPxGBNd8EyquMXynKMwkZbqVhS3w==; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2295e3a85278af42c3844346aaa4b0a320%22%2C%22first_id%22%3A%22188802e57431800-091912c094551f8-26031a51-3686400-188802e57441167%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMTg4ODAyZTU3NDMxODAwLTA5MTkxMmMwOTQ1NTFmOC0yNjAzMWE1MS0zNjg2NDAwLTE4ODgwMmU1NzQ0MTE2NyIsIiRpZGVudGl0eV9sb2dpbl9pZCI6Ijk1ZTNhODUyNzhhZjQyYzM4NDQzNDZhYWE0YjBhMzIwIn0%3D%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%24identity_login_id%22%2C%22value%22%3A%2295e3a85278af42c3844346aaa4b0a320%22%7D%2C%22%24device_id%22%3A%22188802e57431800-091912c094551f8-26031a51-3686400-188802e57441167%22%7D; uc_token=WEBe7c8f7226b44128d10d73547d980bd4023e4acfcdc06463a2e1b0b0b82e6014f; u_id=WEBe7c8f7226b44128d10d73547d980bd4023e4acfcdc06463a2e1b0b0b82e6014f; _ga_L6XJCQTK75=GS1.1.1686623811.18.1.1686624684.60.0.0; RT="z=1&dm=www.mexc.com&si=5789a837-5d7f-45ac-9573-1ef7dde3bf2d&ss=lito9nzn&sl=6&tt=8aa&bcn=%2F%2F684d0d4b.akstat.io%2F&ld=80ks&nu=9y8m6cy&cl=k04w"'
logDingDingConfig:
  accessToken: "5a085bb14f5d65878fa08bf352a33f612b2106cfb3ceb0ace0d977dfba642488"
  secrect: "SEC52054da55de4c272dd456c2c6d4c477433362f2604da4ca8da189918ff88d755"
errorDingDingConfig:
  accessToken: "a6a46f11cfd0a345d90167c22a67bdbe787b5dc72234540ccfe6ebc7e5d86416"
  secrect: "SEC07ebf2d23b2c672cf1834a0109783b758cf80289dcb7f1092b18fd250d1ea1f5"
params:
  number: 9999
  minRatio: 0.8 # base 10000
  maxRatio: 2 # base 10000
  profitRatio: 1 # base 10000
  closeTimeOut: 60000 # ms
  klineRatio: 50.0 # base 10000
  klinePauseDuration: 30000 # ms
  clientTimeOut: 80 # ms
  clientTimeOutPauseDuration: 5000 # ms
  waitDuration: 18000 # ms

